testapp/Models/BooksFilteredModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using testapp.Model;
using X.PagedList;

namespace testapp.Models
{
    public class BooksFilteredModel
    {
        public int PageSize { get; set; } = 10;
        public int Page { get; set; } = 1;
        public IPagedList<Book> Books { get; set; }

        public void ProcessData(IQueryable<Book> books)
        {
            Books = FilterData(books).OrderByDescending(x => x.Id).ToPagedList(Page, PageSize);
        }

        public IQueryable<Book> FilterData(IQueryable<Book> books)
        {
            return books;
        }

    }
}

testapp/Models/GenresFilteredModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using testapp.Model;
using X.PagedList;

namespace testapp.Models
{
    public class GenresFilteredModel
    {
        public int PageSize { get; set; } = 10;
        public int Page { get; set; } = 1;
        public IPagedList<Genre> Genres { get; set; }

        public void ProcessData(IQueryable<Genre> genres)
        {
            Genres = FilterData(genres).OrderByDescending(x => x.Id).ToPagedList(Page, PageSize);
        }

        public IQueryable<Genre> FilterData(IQueryable<Genre> genres)
        {
            return genres;
        }
    }
}

testapp/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using testapp.Model;
using testapp.Model.Interfaces;
using testapp.Model.Repositories;
using testapp.Models;

namespace testapp.Controllers
{
    public class BooksController : Controller
    {
        public IBooksRepository BooksRepository { get; set; }
        public IGenresRepository GenresRepository { get; set; }
        public IUnitOfWork UnitOfWork { get; set; }

        public BooksController(IBooksRepository booksRepository, IGenresRepository genresRepository, IUnitOfWork unitOfWork)
        {
            BooksRepository = booksRepository;
            GenresRepository = genresRepository;
            UnitOfWork = unitOfWork;
        }

        // GET: Books
        public ActionResult Index(BooksFilteredModel filteredModel)
        {
            var books = BooksRepository.FindAll();
            filteredModel.ProcessData(books);

            return View(filteredModel);
        }

        public ActionResult Create()
        {
            ViewBag.Genres = new SelectList(GenresRepository.FindAll().ToList(), "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Book model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Genres = new SelectList(GenresRepository.FindAll().ToList(), "Id", "Name");
                return View(model);
            }

            BooksRepository.Insert(model);
            UnitOfWork.Commit();

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var book = BooksRepository.GetById(id);

            ViewBag.Genres = new SelectList(GenresRepository.FindAll().ToList(), "Id", "Name");
            return View(book);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Book model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Genres = new SelectList(GenresRepository.FindAll().ToList(), "Id", "Name");
                return View(model);
            }

            var book = BooksRepository.GetById(model.Id);
            book.GenreId = model.GenreId;
            book.Author = model.Author;
            book.Title = model.Title;
            book.PublishYear = model.PublishYear;
            UnitOfWork.Commit();

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var book = BooksRepository.GetById(id);
            BooksRepository.Delete(book);
            UnitOfWork.Commit();
            return RedirectToAction("Index");
        }
    }
}

testapp/Controllers/GenresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using testapp.Model;
using testapp.Model.Interfaces;
using testapp.Model.Repositories;
using testapp.Models;

namespace testapp.Controllers
{
    public class GenresController : Controller
    {
        public IGenresRepository GenresRepository { get; set; }
        public IUnitOfWork UnitOfWork { get; set; }

        public GenresController(IGenresRepository genresRepository, IUnitOfWork unitOfWork)
        {
            GenresRepository = genresRepository;
            UnitOfWork = unitOfWork;
        }
        // GET: Genres
        public ActionResult Index(GenresFilteredModel filteredModel)
        {
            var genres = GenresRepository.FindAll();
            var g = GenresRepository.FindAll().ToList();
            filteredModel.ProcessData(genres);

            return View(filteredModel);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Genre model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            GenresRepository.Insert(model);
            UnitOfWork.Commit();

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var book = GenresRepository.GetById(id);

            return View(book);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Genre model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var genre = GenresRepository.GetById(model.Id);
            genre.Name = model.Name;
            UnitOfWork.Commit();

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var genre = GenresRepository.GetById(id);
            GenresRepository.Delete(genre);
            UnitOfWork.Commit();
            return RedirectToAction("Index");
        }
    }
}

testapp/Views/Books/Create.cshtml
@model testapp.Model.Book
@{
    var genres = (SelectList) ViewBag.Genres;
}

<section class="py-5">
    <div class="col-lg-12 mb-5">
        <div class="card">
            <div class="card-header">
                <h3 class="h6 text-uppercase mb-0">All form elements</h3>
            </div>
            <div class="card-body">
                <form method="POST" class="form-horizontal">
                    @Html.AntiForgeryToken()
                    <div class="form-group row">
                        <label class="col-md-3 form-control-label">Title</label>
                        <div class="col-md-9">
                            <input id="Title" name="Title" type="text" class="form-control" required>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-md-3 form-control-label">Author</label>
                        <div class="col-md-9">
                            <input id="Author" name="Author" type="text" class="form-control" required>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-md-3 form-control-label">Year</label>
                        <div class="col-md-9">
                            <input id="PublishYear" name="PublishYear" type="text" class="form-control" required>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-md-3 form-control-label">Genre</label>
                        <div class="col-md-9 select mb-3">
                            <select name="GenreId" class="form-control">
                                @foreach (var genre in genres)
                                {
                                    <option value="@genre.Value">@genre.Text</option>
                                }
                            </select>
                        </div>
                    </div>
                    <div class="line"></div>
                    <div class="form-group row">
                        <div class="col-md-9 ml-auto">
                            <button type="submit" class="btn btn-primary">Save changes</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

testapp/Views/Books/Edit.cshtml
@model testapp.Model.Book
@{
    var genres = (SelectList)ViewBag.Genres;
}

<section class="py-5">
    <div class="col-lg-12 mb-5">
        <div class="card">
            <div class="card-header">
                <h3 class="h6 text-uppercase mb-0">All form elements</h3>
            </div>
            <div class="card-body">
                <form method="POST" class="form-horizontal">
                    @Html.AntiForgeryToken()
                    <div class="form-group row">
                        <label class="col-md-3 form-control-label">Title</label>
                        <div class="col-md-9">
                            <input id="Title" name="Title" type="text" class="form-control" required value="@Model.Title">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-md-3 form-control-label">Author</label>
                        <div class="col-md-9">
                            <input id="Author" name="Author" type="text" class="form-control" required value="@Model.Author">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-md-3 form-control-label">Year</label>
                        <div class="col-md-9">
                            <input id="PublishYear" name="PublishYear" type="text" class="form-control" required value="@Model.PublishYear">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-md-3 form-control-label">Genre</label>
                        <div class="col-md-9 select mb-3">
                            <select name="GenreId" class="form-control">
                                @foreach (var genre in genres)
                                {
                                    <option value="@genre.Value" @(Model.GenreId.ToString().Equals(genre.Value) ? "selected" : "")>@genre.Text</option>
                                }
                            </select>
                        </div>
                    </div>
                    <div class="line"></div>
                    <div class="form-group row">
                        <div class="col-md-9 ml-auto">
                            <button type="submit" class="btn btn-primary">Save changes</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

testapp/Views/Books/Index.cshtml
@model testapp.Models.BooksFilteredModel
<section class="py-5">
    <div class="row">
        <div class="col-lg-12 mb-4">
            <div class="card">
                <div class="card-header">
                    <h6 class="text-uppercase mb-0">Books</h6>
                </div>
                <div class="card-body">
                    <a href="@Url.Action("Create")" class="btn btn-primary mb-4">Add Book</a>
                    <table class="table card-text">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Title</th>
                            <th>Author</th>
                            <th>Year</th>
                            <th>Genre</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @if (Model.Books.Any())
                        {
                            foreach (var book in Model.Books)
                            {
                                <tr>
                                    <td>@book.Id</td>
                                    <td>@book.Title</td>
                                    <td>@book.Author</td>
                                    <td>@book.PublishYear</td>
                                    <td>@book.Genre.Name</td>
                                    <td>
                                        @Html.ActionLink("Edit", "Edit", new { id = book.Id })
                                        @Html.ActionLink("Delete", "Delete", new { id = book.Id })
                                    </td>
                                </tr>
                            }
                        }
                        else
                        {
                            <tr>
                                <td colspan="5">No Data</td>
                            </tr>
                        }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>

testapp/Views/Genres/Create.cshtml
@model testapp.Model.Genre
@{
    var genres = (SelectList)ViewBag.Genres;
}

<section class="py-5">
    <div class="col-lg-12 mb-5">
        <div class="card">
            <div class="card-header">
                <h3 class="h6 text-uppercase mb-0">Add Genre</h3>
            </div>
            <div class="card-body">
                <form method="POST" class="form-horizontal">
                    @Html.AntiForgeryToken()
                    <div class="form-group row">
                        <label class="col-md-3 form-control-label">Normal</label>
                        <div class="col-md-9">
                            <input id="Name" name="Name" type="text" class="form-control" required>
                        </div>
                    </div>
                    <div class="line"></div>
                    <div class="form-group row">
                        <div class="col-md-9 ml-auto">
                            <button type="submit" class="btn btn-primary">Save changes</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

testapp/Views/Genres/Edit.cshtml
@model testapp.Model.Genre

<section class="py-5">
    <div class="col-lg-12 mb-5">
        <div class="card">
            <div class="card-header">
                <h3 class="h6 text-uppercase mb-0">Add Genre</h3>
            </div>
            <div class="card-body">
                <form method="POST" class="form-horizontal">
                    @Html.AntiForgeryToken()
                    <div class="form-group row">
                        <label class="col-md-3 form-control-label">Normal</label>
                        <input type="hidden" name="Id" value="@Model.Id"/>
                        <div class="col-md-9">
                            <input id="Name" name="Name" type="text" class="form-control" required value="@Model.Name">
                        </div>
                    </div>
                    <div class="line"></div>
                    <div class="form-group row">
                        <div class="col-md-9 ml-auto">
                            <button type="submit" class="btn btn-primary">Save changes</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

testapp/Views/Genres/Index.cshtml
@model testapp.Models.GenresFilteredModel
<section class="py-5">
    <div class="row">
        <div class="col-lg-12 mb-4">
            <div class="card">
                <div class="card-header">
                    <h6 class="text-uppercase mb-0">Genres</h6>
                </div>
                <div class="card-body">
                    <a href="@Url.Action("Create")" class="btn btn-primary mb-4">Add Genre</a>
                    <table class="table card-text">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model.Genres.Any())
                            {
                                foreach (var genre in Model.Genres)
                                {
                                    <tr>
                                        <td>@genre.Id</td>
                                        <td>@genre.Name</td>
                                        <td>
                                            @Html.ActionLink("Edit", "Edit", new { id = genre.Id })
                                            @if (!genre.Books.Any())
                                            {
                                                @Html.ActionLink("Delete", "Delete", new { id = genre.Id })
                                            }
                                        </td>
                                    </tr>
                                }
                            }
                            else
                            {
                                <tr>
                                    <td colspan="5">No Data</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>

testapp/Views/Shared/_Footer.cshtml
<footer class="footer bg-white shadow align-self-end py-3 px-xl-5 w-100">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 text-center text-md-left text-primary">
                <p class="mb-2 mb-md-0">Your company &copy; 2018-2020</p>
            </div>
            <div class="col-md-6 text-center text-md-right text-gray-400">
                <p class="mb-0">Design by <a href="https://bootstrapious.com/admin-templates" class="external text-gray-400">Bootstrapious</a></p>
                <!-- Please do not remove the backlink to us unless you support further theme's development at https://bootstrapious.com/donate. It is part of the license conditions. Thank you for understanding :)-->
            </div>
        </div>
    </div>
</footer>

testapp/Views/Shared/_Header.cshtml
<header class="header">
    <nav class="navbar navbar-expand-lg px-4 py-2 bg-white shadow">
        <a href="#" class="sidebar-toggler text-gray-500 mr-4 mr-lg-5 lead"><i class="fas fa-align-left"></i></a><a href="#" class="navbar-brand font-weight-bold text-uppercase text-base">Books</a>
        @*<ul class="ml-auto d-flex align-items-center list-unstyled mb-0">
            <li class="nav-item">
                <form id="searchForm" class="ml-auto d-none d-lg-block">
                    <div class="form-group position-relative mb-0">
                        <button type="submit" style="top: -3px; left: 0;" class="position-absolute bg-white border-0 p-0"><i class="o-search-magnify-1 text-gray text-lg"></i></button>
                        <input type="search" placeholder="Search ..." class="form-control form-control-sm border-0 no-shadow pl-4">
                    </div>
                </form>
            </li>
            <li class="nav-item dropdown mr-3">
                <a id="notifications" href="http://example.com" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle text-gray-400 px-1"><i class="fa fa-bell"></i><span class="notification-icon"></span></a>
                <div aria-labelledby="notifications" class="dropdown-menu">
                    <a href="#" class="dropdown-item">
                        <div class="d-flex align-items-center">
                            <div class="icon icon-sm bg-violet text-white"><i class="fab fa-twitter"></i></div>
                            <div class="text ml-2">
                                <p class="mb-0">You have 2 followers</p>
                            </div>
                        </div>
                    </a><a href="#" class="dropdown-item">
                        <div class="d-flex align-items-center">
                            <div class="icon icon-sm bg-green text-white"><i class="fas fa-envelope"></i></div>
                            <div class="text ml-2">
                                <p class="mb-0">You have 6 new messages</p>
                            </div>
                        </div>
                    </a><a href="#" class="dropdown-item">
                        <div class="d-flex align-items-center">
                            <div class="icon icon-sm bg-blue text-white"><i class="fas fa-upload"></i></div>
                            <div class="text ml-2">
                                <p class="mb-0">Server rebooted</p>
                            </div>
                        </div>
                    </a><a href="#" class="dropdown-item">
                        <div class="d-flex align-items-center">
                            <div class="icon icon-sm bg-violet text-white"><i class="fab fa-twitter"></i></div>
                            <div class="text ml-2">
                                <p class="mb-0">You have 2 followers</p>
                            </div>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div><a href="#" class="dropdown-item text-center"><small class="font-weight-bold headings-font-family text-uppercase">View all notifications</small></a>
                </div>
            </li>
            <li class="nav-item dropdown ml-auto">
                <a id="userInfo" href="http://example.com" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle"><img src="img/avatar-6.jpg" alt="Jason Doe" style="max-width: 2.5rem;" class="img-fluid rounded-circle shadow"></a>
                <div aria-labelledby="userInfo" class="dropdown-menu">
                    <a href="#" class="dropdown-item"><strong class="d-block text-uppercase headings-font-family">Mark Stephen</strong><small>Web Developer</small></a>
                    <div class="dropdown-divider"></div><a href="#" class="dropdown-item">Settings</a><a href="#" class="dropdown-item">Activity log       </a>
                    <div class="dropdown-divider"></div><a href="login.html" class="dropdown-item">Logout</a>
                </div>
            </li>
        </ul>*@
    </nav>
</header>

testapp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Bubbly - Boootstrap 4 Admin template by Bootstrapious.com</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="~/Content/bootstrap/bootstrap.min.css">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <!-- Google fonts - Popppins for copy-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,800">
    <!-- orion icons-->
    <link rel="stylesheet" href="~/Content/orionicons.css">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="~/Content/style.default.css" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="~/Content/custom.css">
    <!-- Favicon-->
    <link rel="shortcut icon" href="img/favicon.png?3">
    <!-- Tweaks for older IEs-->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<body>
    <!-- navbar-->
    @Html.Partial("_Header")
    <div class="d-flex align-items-stretch">
        @Html.Partial("_Sidebar")
        <div class="page-holder w-100 d-flex flex-wrap">
            <div class="container-fluid px-xl-5">
               @RenderBody()
            </div>
            @Html.Partial("_Footer")
        </div>
    </div>
    <!-- JavaScript files-->

    <script src="~/Scripts/jquery/jquery.min.js"></script>
    <script src="~/Scripts/popper.js/umd/popper.min.js"></script>
    <script src="~/Scripts/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.cookie/jquery.cookie.js"></script>
    <script src="~/Scripts/chart.js/Chart.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
    <script src="~/Scripts/charts-home.js"></script>
    <script src="~/Scripts/front.js"></script>
</body>
</html>

testapp/Views/Shared/_Sidebar.cshtml
<div id="sidebar" class="sidebar py-3">
    <div class="text-gray-400 text-uppercase px-3 px-lg-4 py-4 font-weight-bold small headings-font-family">MAIN</div>
    <ul class="sidebar-menu list-unstyled">
        <li class="sidebar-list-item"><a href="@Url.Action("Index", "Books")" class="sidebar-link text-muted"><i class="o-home-1 mr-3 text-gray"></i><span>Books</span></a></li>
        <li class="sidebar-list-item"><a href="@Url.Action("Index", "Genres")" class="sidebar-link text-muted"><i class="o-sales-up-1 mr-3 text-gray"></i><span>Genres</span></a></li>
        
    </ul>
</div>